### PR TITLE
`REVAMP` UI and Model classes

### LINKED ISSUE #230: [PE-D][Tester C] Wrong display in result panel despite wrongly formatted input
After executing `venue unbook v/swimming pOOL tp/16-18 d/WED`, 
the result panel and list panel displays the venue as ***swimming pOOL*** instead of its original name as ***swimming pool***.

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: benjytan45678/ped#6

### PR DESCRIPTION
**Pull request by jq1836**
Cleaned up the `UI` and `Model` classes.

Fixed #230 while cleaning up code.

### CODE REVIEW

File: src/main/java/seedu/rc4hdb/model/venues/Venue.java [hunk 1]
```diff
@@ -112,9 +111,9 @@ public boolean isSameVenue(VenueName otherVenueName) {
 
     //==================== Start of getters =================================
 
-    public ObservableList<Booking> getObservableBookings() {
+    public List<Booking> getBookings() {
         clearExpiredBookings();
-        return FXCollections.observableArrayList(bookings);
```
Comment (nealetham) [inline src/main/java/seedu/rc4hdb/model/venues/Venue.java:117]: It might be better to pass a copy/unmodifiable observable list.

**Review by nealetham — APPROVED** [review]
LGTM! A lot of varied changes in a single PR.
